Name: BackupApp
Version: 1.0.0
Link: https://github.com/Webiny/BackupApp
Description: Create regular backups and store them on S3 in just a few clicks
Author:
    Name: Webiny LTD
    Email: info@webiny.com
    Link: https://www.webiny.com
